//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change home team.
        /// </summary>
        public static string btnChangeHomeTeam {
            get {
                return ResourceManager.GetString("btnChangeHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string btnChangeLanguage {
            get {
                return ResourceManager.GetString("btnChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change opposite team.
        /// </summary>
        public static string btnChangeOppositeTeam {
            get {
                return ResourceManager.GetString("btnChangeOppositeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string btnStats {
            get {
                return ResourceManager.GetString("btnStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose favorite team.
        /// </summary>
        public static string lblChooseFavoriteTeam {
            get {
                return ResourceManager.GetString("lblChooseFavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose opposite team.
        /// </summary>
        public static string lblChooseOppositeTeam {
            get {
                return ResourceManager.GetString("lblChooseOppositeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose resolution.
        /// </summary>
        public static string lblChooseResolution {
            get {
                return ResourceManager.GetString("lblChooseResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite team:.
        /// </summary>
        public static string lblFavoriteTeam {
            get {
                return ResourceManager.GetString("lblFavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code:.
        /// </summary>
        public static string lblFifaCode {
            get {
                return ResourceManager.GetString("lblFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential:.
        /// </summary>
        public static string lblGoalDifferential {
            get {
                return ResourceManager.GetString("lblGoalDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against:.
        /// </summary>
        public static string lblGoalsAgainst {
            get {
                return ResourceManager.GetString("lblGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored in this match:.
        /// </summary>
        public static string lblGoalScoredInMatch {
            get {
                return ResourceManager.GetString("lblGoalScoredInMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string lblGoalsFor {
            get {
                return ResourceManager.GetString("lblGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is captain:.
        /// </summary>
        public static string lblIsCaptain {
            get {
                return ResourceManager.GetString("lblIsCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string lblLarge {
            get {
                return ResourceManager.GetString("lblLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches lost:.
        /// </summary>
        public static string lblMatchesLost {
            get {
                return ResourceManager.GetString("lblMatchesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches won:.
        /// </summary>
        public static string lblMatchesWon {
            get {
                return ResourceManager.GetString("lblMatchesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string lblMedium {
            get {
                return ResourceManager.GetString("lblMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposite team:.
        /// </summary>
        public static string lblOppositeTeam {
            get {
                return ResourceManager.GetString("lblOppositeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches played:.
        /// </summary>
        public static string lblPlayedMatches {
            get {
                return ResourceManager.GetString("lblPlayedMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblPlayerName {
            get {
                return ResourceManager.GetString("lblPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string lblScore {
            get {
                return ResourceManager.GetString("lblScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number:.
        /// </summary>
        public static string lblShirtNumber {
            get {
                return ResourceManager.GetString("lblShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string lblSmall {
            get {
                return ResourceManager.GetString("lblSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblTeamName {
            get {
                return ResourceManager.GetString("lblTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards in this match:.
        /// </summary>
        public static string lblYCInMatch {
            get {
                return ResourceManager.GetString("lblYCInMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
    }
}
